name: "Check build"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
<<<<<<< HEAD
  rebuild:
    name: Rebuild
    runs-on: ${{ 'ubuntu-latest' }}
    timeout-minutes: ${{ 360 }}
    permissions:
      actions: read
      contents: read
      # security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'c-cpp' ]
        # CodeQL supports [ 'c-cpp', 'csharp', 'go', 'java-kotlin', 'javascript-typescript', 'python', 'ruby', 'swift' ]
        # Use only 'java-kotlin' to analyze code written in Java, Kotlin or both
        # Use only 'javascript-typescript' to analyze code written in JavaScript, TypeScript or both
        # Learn more about CodeQL language support at https://aka.ms/codeql-docs/language-support

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v24

    - name: Build Code using Nix
      run: nix build
=======
  build:
    name: Build
      runs-on: ${{ 'ubuntu-latest' }} 
      timeout-minutes: ${{ 360 }}
      permissions:
        actions: read
        contents: read
      strategy:
        fail-fast: false
        matrix:
          language: ['c-cpp']
      steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          languages: ${{ matrix.language }}
      - name: Build Code using Nix
        run: nix build
>>>>>>> 7fdf44efdd54a6c5387772e23845877f27d5999c
